//  Users  //
export const USERS_GETALL_REQUEST = "USERS_GETALL_REQUEST";
export const USERS_GETALL_SUCCESS = "USERS_GETALL_SUCCESS";
export const USERS_GETALL_ERROR = "USERS_GETALL_ERROR";

export const USERS_CREATE_REQUEST = 'USERS_CREATE_REQUEST';
export const USERS_CREATE_SUCCESS = 'USERS_CREATE_SUCCESS';
export const USERS_CREATE_ERROR = 'USERS_CREATE_ERROR';


// Hubbs  //
export const HUBS_GETALL_REQUEST = "HUBS_GETALL_REQUEST";
export const HUBS_GETALL_SUCCESS = "HUBS_GETALL_SUCCESS";
export const HUBS_GETALL_ERROR = "HUBS_GETALL_ERROR";

