// General //
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_FIRST_LOAD = "SET_FIRST_LOAD";
export const APP_START_GET_HUBS_AND_USERS_REQUEST = 'APP_START_GET_HUBS_AND_USERS_REQUEST';
export const APP_START_GET_HUBS_AND_USERS_SUCCESS = 'APP_START_GET_HUBS_AND_USERS_SUCCESS';
export const APP_START_GET_HUBS_AND_USERS_ERROR = 'APP_START_GET_HUBS_AND_USERS_ERROR';

//  Users  //
export const USERS_GETALL_REQUEST = "USERS_GETALL_REQUEST";
export const USERS_GETALL_SUCCESS = "USERS_GETALL_SUCCESS";
export const USERS_GETALL_ERROR = "USERS_GETALL_ERROR";

export const USERS_CREATE_REQUEST = "USERS_CREATE_REQUEST";
export const USERS_CREATE_SUCCESS = "USERS_CREATE_SUCCESS";
export const USERS_CREATE_ERROR = "USERS_CREATE_ERROR";

// Hubbs  //
export const HUBS_GETALL_REQUEST = "HUBS_GETALL_REQUEST";
export const HUBS_GETALL_SUCCESS = "HUBS_GETALL_SUCCESS";
export const HUBS_GETALL_ERROR = "HUBS_GETALL_ERROR";

// Fractions //
export const FRACTIONS_GETALL_REQUEST = "FRACTIONS_GETALL_REQUEST";
export const FRACTIONS_GETALL_SUCCESS = "FRACTIONS_GETALL_SUCCESS";
export const FRACTIONS_GETALL_ERROR = "FRACTIONS_GETALL_ERROR";

export const FRACTIONS_CREATE_REQUEST = "FRACTIONS_CREATE_REQUEST";
export const FRACTIONS_CREATE_SUCCESS = "FRACTIONS_CREATE_SUCCESS";
export const FRACTIONS_CREATE_ERROR = "FRACTIONS_CREATE_ERROR";
