export const APP_START_HUBS_GETALL_REQUEST = "APP_START_HUBS_GETALL_REQUEST";
export const APP_START_HUBS_GETALL_SUCCESS = "APP_START_HUBS_GETALL_SUCCESS";
export const APP_START_HUBS_GETALL_ERROR = "APP_START_HUBS_GETALL_ERROR";
// export default types = {
//     APP_START_HUBS_GETALL = "APP_START_HUBS_GETALL",
//     APP_START_HUBS_GETALL_SUCCESS = "APP_START_HUBS_GETALL_SUCCESS",
//     APP_START_HUBS_GETALL_ERROR = "APP_START_HUBS_GETALL_ERROR"
// }